version: '4'

services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./db/:/data

  web:
    build: .
    command: python Portal/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - web