# Generated by Django 4.2.11 on 2024-03-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('POP', 'Pop'), ('RK', 'Rock'), ('JZ', 'Jazz'), ('CL', 'Classic')], default='CL', max_length=3)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
